Takes into account all executions for more accuracy
briansrls/Robinhood-for-Google-Finance pull request #4
Opened 2016-12-11 01:55 UTC by quanturium

This adds a little more accuracy to the data but not really any changes in google finance. My guess is google finance does not use the timestamp of the transaction really precisely. 

The second thing that I could not find a way to fix is when a company offers you stocks. In this case it appears in your robinhood portfolio but is neither buy or sell operation so there is no transaction associated to it (as far as I could find on the transaction API)

2016-12-11 18:06 UTC, briansrls requested changes

2016-12-11 18:06 UTC, briansrls commented on gf-export.py
> +                n+=1
I think making this block here is a good idea, but I would like to make sure that moving this under 

```
if order['state'] == "filled":
              trade_count += 1
```
 
doesn't create redundancies later on.  

For example, if we check if the state is filled here, there is no reason to check later on which is nice.  
  
```
 if str(fields[row]["state"]) == "filled" and str(fields[row]["cancel"]) == "None":
              try:
                  if key!="state" and key!="cancel":
                     if key=="average_price" or key=="fees":
                         fields[row][key] = round(float(fields[row][key]),2)
                      line += str(fields[row][key]) + ","
              except:
                  line += ","
```

Here we should be able to remove the opening if statement checking of the state is filled. 

If we don't need to check if this if statement is true (checking if cancel is "none" may also be redundant, I was never sure what that column was for?), then we may not have to add "state" and "cancel" to the desired keys, and then to the new keys list.  Let me know if what I'm saying makes sense.

All in all, your code is certainly an improvement over what exists.  I think you can just remove the if statement I mentioned in the second block here, and check if there is any need to even have state/cancel fields in our desired list.  Test and let me know if that still works, and I'll merge everything.

2016-12-11 18:06 UTC, briansrls commented on gf-export.py
> +desired = ("price", "timestamp", "fees", "quantity", "symbol", "side", "state", "cancel")
Can we remove state, cancel as well?

2016-12-12 02:30 UTC, quanturium commented on gf-export.py
> +                n+=1
Fixed what you've mentioned in latest comments

2016-12-12 03:47 UTC, briansrls approved these changes
Excellent, thanks a lot for the contribution.  I think overall this is a much better way of doing what I wanted in the first place.

2016-12-12 03:47 UTC, merged